openapi: 3.2.0
info:
  title: Switchfly Loyalty OAuth 2 - SSO Authorize API
  description: Switchfly uses **OAuth 2** for the SSO authentication required to communicate with any 3rd party API in order to perform loyalty account actions.
  version: v3.4
tags:
- name: OAuth 2 - SSO Authorize
  description: Switchfly OAuth 2 SSO request to 3rd party
paths:
  /token:
    post:
      tags:
      - OAuth 2 - SSO Authorize
      summary: Endpoint for authentication
      description: This is the token endpoint that will be used either to retrieve a token exchanging the authorization `code` when `grant_type=authorization_code` is used for the SSO.
      operationId: TokenRequest
      requestBody:
        description: Token request body
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              oneOf:
              - $ref: '#/components/schemas/AuthorizationCode'
              - $ref: '#/components/schemas/ClientCredentials'
              - $ref: '#/components/schemas/RefreshToken'
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/AuthorizationCodeTokenResponse'
                - $ref: '#/components/schemas/RefreshTokenTokenResponse'
                - $ref: '#/components/schemas/ClientCredentialsTokenResponse'
components:
  schemas:
    ClientCredentialsTokenResponse:
      type: object
      required:
      - access_token
      properties:
        access_token:
          type: string
          description: The access token issued by the authorization server.
        token_type:
          type: string
          description: Type of token issued.
        expires_in:
          type: integer
          description: The lifetime of the access token in seconds.
    AuthorizationCode:
      required:
      - grant_type
      - client_id
      - code
      - code_verifier
      - redirect_uri
      - scope
      type: object
      properties:
        grant_type:
          type: string
          enum:
          - authorization_code
          description: The type of grant being used in the request
        client_id:
          type: string
        code:
          type: string
        code_verifier:
          type: string
        scope:
          type: string
          enum:
          - profile redeem
        redirect_uri:
          type: string
          example: https://domain.switchfly.com/apps/api/sso/oauth2
    RefreshToken:
      required:
      - grant_type
      - refresh_token
      - redirect_uri
      type: object
      properties:
        grant_type:
          type: string
          enum:
          - refresh_token
        refresh_token:
          type: string
        redirect_uri:
          type: string
    RefreshTokenTokenResponse:
      type: object
      required:
      - access_token
      - refresh_token
      properties:
        access_token:
          type: string
          description: The access token issued by the authorization server.
        token_type:
          type: string
          description: Type of token issued.
        refresh_token:
          type: string
          description: The refresh token issued by the authorization server. (only when using  grant `authorization_code`)
        expires_in:
          type: integer
          description: The lifetime of the access token in seconds.
    AuthorizationCodeTokenResponse:
      type: object
      required:
      - access_token
      - refresh_token
      properties:
        access_token:
          type: string
          description: The access token issued by the authorization server.
        token_type:
          type: string
          description: Type of token issued.
        refresh_token:
          type: string
          description: The refresh token issued by the authorization server. (only when using  grant `authorization_code`)
        expires_in:
          type: integer
          description: The lifetime of the access token in seconds.
    ClientCredentials:
      required:
      - grant_type
      - client_id
      - client_secret
      - scope
      type: object
      properties:
        grant_type:
          type: string
          enum:
          - client_credentials
        client_id:
          type: string
        client_secret:
          type: string
        scope:
          type: string
          enum:
          - profile redeem
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: Uses token retrieved from OAuth 2 SSO token requests
    adminBearerAuth:
      type: http
      scheme: bearer
      description: Uses token retrieved from Machine to Machine OAuth 2 client credentials token request.
